import './globals.css';
import Footer from '@/components/footer';
import Header from '@/components/header';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Ruairí Donaghey',
  description: 'Generated by create next app',
  icons: {
    icon: '/Logo.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
