import type { MetadataRoute } from 'next';

export const dynamic = 'force-static';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: [
          'GPTBot',
          'ClaudeBot',
          'Claude-User',
          'Claude-SearchBot',
          'CCBot',
          'Google-Extended',
          'Applebot-Extended',
          'Facebookbot',
          'Meta-ExternalAgent',
          'Meta-ExternalFetcher',
          'diffbot',
          'PerplexityBot',
          'Perplexity‑User',
          'Omgili',
          'Omgilibot',
          'webzio-extended',
          'ImagesiftBot',
          'Bytespider',
          'TikTokSpider',
          'Amazonbot',
          'Youbot',
          'SemrushBot-OCOB',
          'Petalbot',
          'VelenPublicWebCrawler',
          'TurnitinBot',
          'Timpibot',
          'OAI-SearchBot',
          'ICC-Crawler',
          'AI2Bot',
          'AI2Bot-Dolma',
          'DataForSeoBot',
          'AwarioBot',
          'AwarioSmartBot',
          'AwarioRssBot',
          'Google-CloudVertexBot',
          'PanguBot',
          'Kangaroo Bot',
          'Sentibot',
          'img2dataset',
          'Meltwater',
          'Seekr',
          'peer39_crawler',
          'cohere-ai',
          'cohere-training-data-crawler',
          'DuckAssistBot',
          'Scrapy',
          'Cotoyogi',
          'aiHitBot',
          'Factset_spyderbot',
          'FirecrawlAgent',
        ],
        disallow: '/',
      },
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    sitemap: 'https://donaghey.ie/sitemap.xml',
  };
}
